language: node_js

node_js:
  - "14"
  - "16"

services:
  - postgresql

install:
  - npm i --ignore-scripts

before_script:
  - cp .env.example .env

after_script:
  - npm i -g coveralls
  - npx nyc report --reporter=text-lcov | coveralls
